### ISSUE TITLE
Field should be annotated

### ISSUE THREAD

**Issue by lothrimondWDZ** [holawlo/first_spring#1]
https://github.com/holawlo/first_spring/blob/2f53416718210f90220ae77eb2b26f123e2214f3/src/main/java/trials/MyElement.java#L13
Field should be annotated with `@Column`

**Comment by sdakf** [comment]
https://stackoverflow.com/questions/22735543/column-annotation-absolutly-necessary-in-jpa

**Comment by lothrimondWDZ** [comment]
That's why I didn't write **must**. It's just for increased readability :)
